Source : coursera.org

In [1]:
import numpy as np

### Creating Arrays

In [2]:
# Converting list into numpy arrays

mylist = [1,2,3]
x=np.array(mylist)
x

array([1, 2, 3])

In [3]:
# Alternate way to create numpy arrays

y=np.array([1,2,3])
y

array([1, 2, 3])

In [4]:
# Create multidimensional arrays or matrices

z=np.array([[1,2,3],[4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Finding the number of rows and columns in numpy array or matrix - 2 rows and 3 columns

z.shape

(2, 3)

In [6]:
# Returning even-spaced values with a start, end and interval points

n=np.arange(0,30,5)
n

array([ 0,  5, 10, 15, 20, 25])

In [7]:
# Returning an array with a new shape-> 3 rows and 5 columns. insteaof of np w

n=n.reshape(3,2)
n

array([[ 0,  5],
       [10, 15],
       [20, 25]])

In [8]:
# Returning evenly spaced numbers over a specified number -> 9 evenly spaced numbers from 0 to 4
o=np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [10]:
### Resizing array

o=o.reshape(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [12]:
# Returning ones array with the shape defined

p=np.ones((3,4))
p

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# Returning zeros array with the shape defined
q=np.zeros((3,4))
q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# Identity matrix with ones
r=np.eye(3)
r

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Extracting or constructional diagonal array
np.diag(y)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [23]:
# Creating an array repeating list
a=np.array([1,2,3]*3)
a

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [24]:
a=np.array([1,2,3])
a=np.tile(a,3)
a

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [25]:
# Repeating elements of an array

np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Combining Arrays

In [27]:
p=np.ones([2,3],int) # 2X3 integer array
p

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
# Stacking arrays in a sequence vertically
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [29]:
# Stacking arrays in a sequence horizontally
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

### Operations

In [30]:
# Addition and Subtraction
print(x+y)
print(x-y)

[2 4 6]
[0 0 0]


In [32]:
# Multiplication and Division

print (x*y)
print (x/y)

[1 4 9]
[1. 1. 1.]


In [33]:
# Element-wise power
print(x**y)

[ 1  4 27]


In [34]:
# Dot Product for instance 2 matrices , the first one horizontally and the 2nd vertically arranged -> 1*4 + 2*5 + 3*6
x.dot(y)

14

In [36]:
# Transposing arrays 
z = np.array([y, y**2])
z

array([[1, 2, 3],
       [1, 4, 9]])

In [37]:
z.shape # Find the shape of the array before transposing

(2, 3)

In [38]:
z.T # Transposing array

array([[1, 1],
       [2, 4],
       [3, 9]])

In [39]:
z.T.shape # Shape of transposed array

(3, 2)

In [42]:
# Finding the datatype of the matrix and elements

type(z)

numpy.ndarray

In [43]:
z.dtype

dtype('int64')

In [44]:
# Converting integer to float
z=z.astype(float)
z.dtype

dtype('float64')

### Math Functions 

In [45]:
a=np.array([-4,-2,1,3,5])

In [46]:
a.sum()

3

In [47]:
a.max()

5

In [48]:
a.min()

-4

In [49]:
a.mean()

0.6

In [50]:
a.std()

3.2619012860600183

In [52]:
# Returning the max and min index numbers of the array
a.argmax()

4

In [53]:
a.argmin()

0

### Indexing /Slicing

In [54]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [55]:
# Getting a specific value based on index .Index 0 is the first one

s[0], s[4], s[-1]

(0, 16, 144)

In [56]:
# Elements 1 through 5. 1 being the seconf one because counter starts at 0.
s[1:5]

array([ 1,  4,  9, 16])

In [57]:
# counting backwards

s[-4:]

array([ 81, 100, 121, 144])

In [58]:
#A second : can be used to indicate step-size. array[start:stop:stepsize]

s[-5::-2]

array([64, 36, 16,  4,  0])

In [59]:
# Multi-dimensional array

r=np.arange(36)  # < 36
r.resize(6,6) # Getting 6X6 matrix
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [69]:
# Slicing the array based on index number. The index starts from 0. In this case Row 0, column 0 

r[0, 0]

0

In [70]:
r[1, 2]

8

In [71]:
r[2, 2]

14

In [72]:
# Using : to select a range of rows or columns
r[3, 3:6]

array([21, 22, 23])

In [73]:
r[3, 2:5]

array([20, 21, 22])

In [74]:
#selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.
r[-1, ::2]


array([30, 32, 34])

In [75]:
# Conditional Indexing . Selecting values from array that are greater than 30
r[r > 30]

array([31, 32, 33, 34, 35])

In [81]:
# Assigning all the values greater than 30 to 30
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [85]:
# Asking Python where in the array is r > 28. Python shows the placeholders where r > 28 , 
# the first array being row indices and second one being column indices. Note: Index starts with 0.
np.where(r > 28)

(array([4, 5, 5, 5, 5, 5, 5]), array([5, 0, 1, 2, 3, 4, 5]))

### Copying data

In [86]:
# Slicing r

r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [87]:
# Setting the slice value to 0 for the first 2 rows

r2[:2]=0
r2

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [12, 13, 14]])

In [88]:
# r has changes too even if the changes were made to r2. 
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [89]:
# Copying is the best option rather than slicing 

r_copy=r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [90]:
# if r_copy is modified, r will not change

r_copy[:]=10
print(r_copy,'\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


### Iterating over arrays


In [94]:
# Creating a 4 x3 matrix qith random integers frm 0, 10

test=np.random.randint(0,10,(4,3))
test

array([[7, 0, 0],
       [7, 7, 2],
       [2, 8, 7],
       [1, 4, 0]])

In [96]:
# Iterating by row
for row in test:
    print(row)

[7 0 0]
[7 7 2]
[2 8 7]
[1 4 0]


In [97]:
# Iterating by index
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [7 0 0]
row 1 is [7 7 2]
row 2 is [2 8 7]
row 3 is [1 4 0]


In [98]:
# Iterating over multiple iterables
test2 = test**2
test2

array([[49,  0,  0],
       [49, 49,  4],
       [ 4, 64, 49],
       [ 1, 16,  0]])

In [99]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[7 0 0] + [49  0  0] = [56  0  0]
[7 7 2] + [49 49  4] = [56 56  6]
[2 8 7] + [ 4 64 49] = [ 6 72 56]
[1 4 0] + [ 1 16  0] = [ 2 20  0]
